# Generated by Django 5.1.5 on 2025-02-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitamedica',
            name='data_emissao',
            field=models.DateField(),
        ),
    ]
